// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzj1EHimaSKqoGqtcSkeQgFXXPu0iyx-U',
    appId: '1:413594178591:web:4a242dfd970d1a2946712a',
    messagingSenderId: '413594178591',
    projectId: 'purrnote-app',
    authDomain: 'purrnote-app.firebaseapp.com',
    storageBucket: 'purrnote-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JwCUCOC4KkccFh8mzZp82MKxg7wjRQ8',
    appId: '1:413594178591:android:2307f7e50f55f2c646712a',
    messagingSenderId: '413594178591',
    projectId: 'purrnote-app',
    storageBucket: 'purrnote-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfLUATSgR2cWovo7YK_COzjm5LpvaW4Y',
    appId: '1:413594178591:ios:ffb442ca6814574a46712a',
    messagingSenderId: '413594178591',
    projectId: 'purrnote-app',
    storageBucket: 'purrnote-app.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFfLUATSgR2cWovo7YK_COzjm5LpvaW4Y',
    appId: '1:413594178591:ios:ffb442ca6814574a46712a',
    messagingSenderId: '413594178591',
    projectId: 'purrnote-app',
    storageBucket: 'purrnote-app.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzj1EHimaSKqoGqtcSkeQgFXXPu0iyx-U',
    appId: '1:413594178591:web:30136c0516045d8b46712a',
    messagingSenderId: '413594178591',
    projectId: 'purrnote-app',
    authDomain: 'purrnote-app.firebaseapp.com',
    storageBucket: 'purrnote-app.appspot.com',
  );

}